spring.application.name=usuarios

aws.cognito.region=${AWS_COGNITO_REGION:us-east-1}
aws.cognito.user-pool-id=${AWS_COGNITO_USER_POOL_ID}
aws.cognito.client-id=${AWS_COGNITO_CLIENT_ID}

aws.access-key-id=${AWS_ACCESS_KEY_ID}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}

server.port=${PORT:8082}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true